//import packages
import 'package:flutter/material.dart';

class TournoumentDetail {
  final String title;
  final String gameMode;
  final String tourMode;
  final String description;

  final String region;
  final String game;

  final String creator;
  final String creatorImageUrl;

  final String imageUrl;
  final String bgImageUrl;

  final Color colorBegin;
  final Color colorEnd;

  final Color primaryShadowColor;
  final Color secondaryShadowColor;

  final int enteredPlayers;
  final int totalPlayers;

  final double prize;

  final bool isPublic;
  final double feePrice;

  TournoumentDetail({
    @required this.title,
    @required this.gameMode,
    @required this.tourMode,
    @required this.description,
    @required this.region,
    @required this.game,
    @required this.creator,
    @required this.creatorImageUrl,
    @required this.imageUrl,
    this.bgImageUrl,
    @required this.colorBegin,
    @required this.colorEnd,
    @required this.primaryShadowColor,
    @required this.secondaryShadowColor,
    @required this.enteredPlayers,
    @required this.totalPlayers,
    @required this.prize,
    @required this.isPublic,
    @required this.feePrice,
  });

  TournoumentDetail.fromJson(Map<String, dynamic> fromJson)
      : title = fromJson['title'],
        gameMode = fromJson['gameMode'],
        description = fromJson['description'],
        tourMode = fromJson['tourMode'],
        region = fromJson['region'],
        game = fromJson['game'],
        creator = fromJson['creator'],
        creatorImageUrl = fromJson['creatorImg'],
        imageUrl = fromJson['imageUrl'],
        bgImageUrl = fromJson['bgImageUrl'],
        colorBegin = fromJson['colorBegin'],
        colorEnd = fromJson['colorEnd'],
        primaryShadowColor = fromJson['primaryColor'],
        secondaryShadowColor = fromJson['secondaryColor'],
        enteredPlayers = fromJson['enteredPlayers'],
        totalPlayers = fromJson['totalPlayers'],
        prize = fromJson['prize'],
        isPublic = fromJson['isPublic'],
        feePrice = fromJson['feePrice'];
}

final List<TournoumentDetail> listTournoument = [
  TournoumentDetail(
    title: 'Pro Fncs ZoneWars',
    gameMode: 'ZoneWar',
    tourMode: 'Solo',
    description: 'tournument',
    region: 'ME',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/renegade.png',
    colorBegin: Color(0xFFDDAE90),
    colorEnd: Color(0xFFFFD8B2), //opacity 50
    primaryShadowColor: Color(0xFFDDAE90),
    secondaryShadowColor: Color(0xFFD48941),
    enteredPlayers: 6,
    totalPlayers: 16,
    prize: 9.99,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Duo',
    description: 'Compete with eachother to get the prize',
    region: 'ME',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/skull.png',
    colorBegin: Color(0xFFA75EBA),
    colorEnd: Color(0xFFEEAEFF), // 50 opacity
    primaryShadowColor: Color(0xFFA03CBA),
    secondaryShadowColor: Color(0xFF600079),
    enteredPlayers: 43,
    totalPlayers: 98,
    prize: 50.0,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Duo',
    description: 'Compete with eachother to get the prize',
    region: 'EU',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/focus.png',
    colorBegin: Color(0xFF5FD2DA),
    colorEnd: Color(0xFFB8FBFF),
    primaryShadowColor: Color(0xFF43B9C0),
    secondaryShadowColor: Color(0xFF006268),
    enteredPlayers: 30,
    totalPlayers: 98,
    prize: 1.1,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Squad',
    description: 'Compete with eachother to get the prize',
    region: 'ME',
    game: 'valorant',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/phoenix.png',
    colorBegin: Color(0xFFE2E479),
    colorEnd: Color(0xFFECEE8C),
    primaryShadowColor: Color(0xFFF3F498),
    secondaryShadowColor: Color(0xFF869C00),
    enteredPlayers: 5,
    totalPlayers: 8,
    prize: 1.1,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Pro Fncs ZoneWars',
    gameMode: 'Battle Royale',
    tourMode: 'Solo',
    description: 'tournument',
    region: 'ME',
    game: 'valorant',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/renegade.png',
    colorBegin: Color(0xFFDBAB7E),
    colorEnd: Color(0xFFFFD3AC),
    primaryShadowColor: Color(0xFFB77C45),
    secondaryShadowColor: Color(0xFF994A00),
    enteredPlayers: 6,
    totalPlayers: 16,
    prize: 9.99,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Duo',
    description: 'Compete with eachother to get the prize',
    region: 'ME',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/skull.png',
    colorBegin: Color(0xFFA75EBA),
    colorEnd: Color(0xFFCF7BE4),
    primaryShadowColor: Color(0xFF8B32A1),
    secondaryShadowColor: Color(0xFF600079),
    enteredPlayers: 43,
    totalPlayers: 98,
    prize: 50.0,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Duo',
    description: 'Compete with eachother to get the prize',
    region: 'EU',
    game: 'rainbow-six',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/focus.png',
    colorBegin: Color(0xFF5FD2DA),
    colorEnd: Color(0xFFB8FBFF),
    primaryShadowColor: Color(0xFF43B9C0),
    secondaryShadowColor: Color(0xFF006268),
    enteredPlayers: 30,
    totalPlayers: 98,
    prize: 1.1,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Squad',
    description: 'Compete with eachother to get the prize',
    region: 'ME',
    game: 'apex-legends',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/phoenix.png',
    colorBegin: Color(0xFFE2E479),
    colorEnd: Color(0xFFECEE8C),
    primaryShadowColor: Color(0xFFF3F498),
    secondaryShadowColor: Color(0xFF869C00),
    enteredPlayers: 5,
    totalPlayers: 8,
    prize: 1.1,
    isPublic: false,
    feePrice: 0.0,
  ),
];

final List<TournoumentDetail> getReadyTournouments = [
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Duo',
    description: 'Compete with eachother to get the prize',
    region: 'EU',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/focus.png',
    colorBegin: Color(0xFF5FD2DA),
    colorEnd: Color(0xFFB8FBFF),
    primaryShadowColor: Color(0xFF43B9C0),
    secondaryShadowColor: Color(0xFF006268),
    enteredPlayers: 30,
    totalPlayers: 98,
    prize: 1.1,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Pro Fncs ZoneWars',
    gameMode: 'ZoneWar',
    tourMode: 'Solo',
    description: 'tournument',
    region: 'ME',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/renegade.png',
    bgImageUrl: 'assets/tourImages/renegadeForeground.png',
    colorBegin: Color(0xFFDBAB7E),
    colorEnd: Color(0xFFFFD3AC),
    primaryShadowColor: Color(0xFFB77C45),
    secondaryShadowColor: Color(0xFF994A00),
    enteredPlayers: 6,
    totalPlayers: 16,
    prize: 9.99,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Arena Scrims Tier1',
    gameMode: 'Battle Royale',
    tourMode: 'Duo',
    description: 'Compete with eachother to get the prize',
    region: 'EU',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/focus.png',
    colorBegin: Color(0xFF5FD2DA),
    colorEnd: Color(0xFFB8FBFF),
    primaryShadowColor: Color(0xFF43B9C0),
    secondaryShadowColor: Color(0xFF006268),
    enteredPlayers: 30,
    totalPlayers: 98,
    prize: 1.1,
    isPublic: false,
    feePrice: 0.0,
  ),
  TournoumentDetail(
    title: 'Pro Fncs ZoneWars',
    gameMode: 'ZoneWar',
    tourMode: 'Solo',
    description: 'tournument',
    region: 'ME',
    game: 'fortnite',
    creator: 'Arena',
    creatorImageUrl: 'assets/arenaPng.png',
    imageUrl: 'assets/tourImages/renegade.png',
    bgImageUrl: 'assets/tourImages/renegadeForeground.png',
    colorBegin: Color(0xFFDBAB7E),
    colorEnd: Color(0xFFFFD3AC),
    primaryShadowColor: Color(0xFFB77C45),
    secondaryShadowColor: Color(0xFF994A00),
    enteredPlayers: 6,
    totalPlayers: 16,
    prize: 9.99,
    isPublic: false,
    feePrice: 0.0,
  ),
];
